# Generated by Django 3.0.9 on 2023-07-23 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('mobile', models.CharField(default='', max_length=15, null=True)),
                ('gender', models.CharField(default='', max_length=10, null=True)),
                ('nationality', models.CharField(default='', max_length=50, null=True)),
                ('biodata', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('photo', models.ImageField(default=None, null=True, upload_to='uploads/')),
                ('father_spouse', models.CharField(default='', max_length=100, null=True)),
                ('expertise', models.CharField(default='', max_length=100, null=True)),
                ('address1', models.CharField(default='', max_length=100, null=True)),
                ('address2', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=50, null=True)),
                ('district', models.CharField(default='', max_length=50, null=True)),
                ('state', models.CharField(default='', max_length=50, null=True)),
                ('pincode', models.CharField(default='', max_length=10, null=True)),
                ('inst_state', models.CharField(default='', max_length=50, null=True)),
                ('inst_district', models.CharField(default='', max_length=50, null=True)),
                ('institution', models.CharField(default='', max_length=100, null=True)),
                ('designation', models.CharField(default='', max_length=100, null=True)),
                ('department', models.CharField(default='', max_length=100, null=True)),
                ('qualifying_degree', models.CharField(choices=[('M.S.', 'M.S.'), ('M.D.', 'M.D.'), ('PhD', 'PhD')], default='M.S.', max_length=5)),
                ('degree_awarded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True)),
                ('degree_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('thesis_title', models.CharField(default='', max_length=100, null=True)),
                ('subject', models.CharField(default='', max_length=200, null=True)),
                ('supervisor_guide', models.CharField(default='', max_length=200, null=True)),
                ('university_institute', models.CharField(default='', max_length=200, null=True)),
                ('research_work_details', models.TextField(default='', max_length=6000, null=True)),
                ('project_title', models.CharField(default='', max_length=500, null=True)),
                ('project_summary', models.TextField(default='', max_length=500, null=True)),
                ('keywords', models.CharField(default='', max_length=180, null=True)),
                ('objectives', models.TextField(default='', max_length=1500, null=True)),
                ('result', models.TextField(default='', max_length=1500, null=True)),
                ('methodology_work_plan', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('mentor_institute', models.CharField(default='', max_length=100, null=True)),
                ('mentor_email', models.EmailField(default='', max_length=254, null=True)),
                ('mentor_name', models.CharField(default='', max_length=100, null=True)),
                ('registrar_email', models.EmailField(default='', max_length=254, null=True)),
                ('phd_scholars_working', models.PositiveIntegerField(default=1, null=True)),
                ('postdoc_fellows_working', models.PositiveIntegerField(default=1, null=True)),
                ('Undertaking', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Endorsement', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Birth', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('CV', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Plagiarism', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Pub2', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Caste', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Degree', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('thesis', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('Pub1', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('reference_number', models.CharField(default='', max_length=8, unique=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('reference1_name_address', models.TextField(default='', max_length=1000, null=True)),
                ('reference1_email', models.EmailField(default='', max_length=254, null=True)),
                ('reference1_contact', models.CharField(default='', max_length=50, null=True)),
                ('reference2_name_address', models.TextField(default='', max_length=1000, null=True)),
                ('reference2_email', models.EmailField(default='', max_length=254, null=True)),
                ('reference2_contact', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
